Repository UKHomeOffice/core-cloud-terraform-modules, pull requests merged in 2024-04, with the labels that each got.

#63 ci: implement tagging of repository on change
  .github/workflows/pull-request-semver-label-check.yaml
  .github/workflows/pull-request-semver-tag-merge.yaml
Labels: minor

#64 Add HTTPS enforcement to CUR bucket policy
  modules/aws/cost_usage_reports/main.tf
Labels: minor

#75 Refactoring of Groups, Users and Memberships modules
  modules/aws/group_user_memberships/main.tf
  modules/aws/group_user_memberships/variables.tf
  modules/aws/groups/main.tf
  modules/aws/groups/outputs.tf
  modules/aws/groups/variables.tf
  modules/aws/users/.terraform.lock.hcl
  modules/aws/users/main.tf
  modules/aws/users/outputs.tf
  modules/aws/users/variables.tf
Labels: major

#76 Update group output to use group_id
  modules/aws/groups/outputs.tf
Labels: patch
