Repository UKHomeOffice/core-cloud-terraform-modules, pull requests merged in 2025-02, with the labels that each got.

#200 CCL-1906 - initial backup vault module
  modules/aws/backup_vault/README.md
  modules/aws/backup_vault/main.tf
  modules/aws/backup_vault/variables.tf
Labels: minor

#202 CCL-1906 - add tags to backup vault module
  modules/aws/backup_vault/main.tf
  modules/aws/backup_vault/variables.tf
Labels: patch

#203 Update backup vault module.
  modules/aws/backup_vault/README.md
  modules/aws/backup_vault/main.tf
  modules/aws/backup_vault/variables.tf
Labels: minor

#201 CCL-1546: Ingress TF code with docs
  .trivyignore
  modules/aws/networking/ingress/README.md
  modules/aws/networking/ingress/acm/README.md
  modules/aws/networking/ingress/acm/main.tf
  modules/aws/networking/ingress/acm/outputs.tf
  modules/aws/networking/ingress/acm/variables.tf
  modules/aws/networking/ingress/alb/README.md
  modules/aws/networking/ingress/alb/data.tf
  modules/aws/networking/ingress/alb/main.tf
  modules/aws/networking/ingress/alb/outputs.tf
  modules/aws/networking/ingress/alb/variables.tf
  modules/aws/networking/ingress/nlb-ips/README.md
  modules/aws/networking/ingress/nlb-ips/external.tf
  modules/aws/networking/ingress/nlb-ips/variables.tf
  modules/aws/networking/ingress/nlb/README.md
  modules/aws/networking/ingress/nlb/data.tf
  modules/aws/networking/ingress/nlb/external.tf
  modules/aws/networking/ingress/nlb/internal.tf
  modules/aws/networking/ingress/nlb/outputs.tf
  modules/aws/networking/ingress/nlb/variables.tf
  modules/aws/networking/ingress/private-subnets/README.md
  modules/aws/networking/ingress/private-subnets/main.tf
  modules/aws/networking/ingress/private-subnets/outputs.tf
  modules/aws/networking/ingress/private-subnets/variables.tf
  modules/aws/networking/ingress/route53-private-zone/README.md
  modules/aws/networking/ingress/route53-private-zone/main.tf
  modules/aws/networking/ingress/route53-private-zone/outputs.tf
  modules/aws/networking/ingress/route53-private-zone/variables.tf
  modules/aws/networking/ingress/route53-public-zone/README.md
  modules/aws/networking/ingress/route53-public-zone/main.tf
  modules/aws/networking/ingress/route53-public-zone/variables.tf
Labels: major

#204 CCL1905 - update backup vault module
  modules/aws/backup_vault/README.md
  modules/aws/backup_vault/main.tf
  modules/aws/backup_vault/variables.tf
Labels: minor

#206 CCL-1905 - remove backup global settings resource
  modules/aws/backup_vault/README.md
  modules/aws/backup_vault/main.tf
  modules/aws/backup_vault/variables.tf
Labels: patch

#205 CCL-1531: Terraform with docs for tenant metadata capture from JSD
  .trivyignore
  modules/aws/tenant_metadata/api_gateway/README.md
  modules/aws/tenant_metadata/api_gateway/main.tf
  modules/aws/tenant_metadata/api_gateway/outputs.tf
  modules/aws/tenant_metadata/api_gateway/variables.tf
  modules/aws/tenant_metadata/dynamodb/README.md
  modules/aws/tenant_metadata/dynamodb/main.tf
  modules/aws/tenant_metadata/dynamodb/outputs.tf
  modules/aws/tenant_metadata/dynamodb/variables.tf
  modules/aws/tenant_metadata/iam/README.md
  modules/aws/tenant_metadata/iam/main.tf
  modules/aws/tenant_metadata/iam/outputs.tf
  modules/aws/tenant_metadata/iam/variables.tf
Labels: major

#207 CCL-1531: Allow api-gateway to write to cwlogs
  modules/aws/tenant_metadata/api_gateway/main.tf
  modules/aws/tenant_metadata/api_gateway/variables.tf
  modules/aws/tenant_metadata/iam/main.tf
Labels: major

#208 Add type info to variable.
  modules/aws/networking/ctn-connect-attachment/main.tf
  modules/aws/networking/ctn-connect-attachment/variables.tf
Labels: minor

#213 adding fetch-secret module
  modules/aws/secrets/fetch-secret/main.tf
  modules/aws/secrets/fetch-secret/outputs.tf
  modules/aws/secrets/fetch-secret/variables.tf
Labels: minor

#214 adding tgw-vpc-attachment module
  modules/aws/networking/tgw-vpc-attachment/.terraform-docs.yml
  modules/aws/networking/tgw-vpc-attachment/README.md
  modules/aws/networking/tgw-vpc-attachment/main.tf
  modules/aws/networking/tgw-vpc-attachment/variables.tf
Labels: patch

#215 adding module for cw-logs-destination
  modules/aws/logging/cw-logs-destination/README.md
  modules/aws/logging/cw-logs-destination/main.tf
  modules/aws/logging/cw-logs-destination/outputs.tf
  modules/aws/logging/cw-logs-destination/variables.tf
  modules/aws/secrets/fetch-secret/README.md
Labels: minor

#217 adding gateway prpagtion option in module
  modules/aws/networking/tgw-vpc-attachment/README.md
  modules/aws/networking/tgw-vpc-attachment/main.tf
  modules/aws/networking/tgw-vpc-attachment/variables.tf
Labels: minor

#218 adding name tag in module
  modules/aws/networking/tgw-vpc-attachment/README.md
  modules/aws/networking/tgw-vpc-attachment/main.tf
  modules/aws/networking/tgw-vpc-attachment/variables.tf
Labels: minor

#219 adding a module for event-bridge-rule
  modules/aws/event_bridge/event_bridge_rule/README.md
  modules/aws/event_bridge/event_bridge_rule/main.tf
  modules/aws/event_bridge/event_bridge_rule/outputs.tf
  modules/aws/event_bridge/event_bridge_rule/variables.tf
Labels: patch
