Repository UKHomeOffice/core-cloud-terraform-modules, pull requests merged in 2025-03, with the labels that each got.

#221 CCL-2176: Isolated AWS Accounts ingress
  .trivyignore
  modules/aws/networking/ingress/dns-isolated/route53-public-zone/README.md
  modules/aws/networking/ingress/dns-isolated/route53-public-zone/main.tf
  modules/aws/networking/ingress/dns-isolated/route53-public-zone/variables.tf
  modules/aws/networking/ingress/nlb-isolated/README.md
  modules/aws/networking/ingress/nlb-isolated/data.tf
  modules/aws/networking/ingress/nlb-isolated/external.tf
  modules/aws/networking/ingress/nlb-isolated/outputs.tf
  modules/aws/networking/ingress/nlb-isolated/variables.tf
Labels: minor

#223 Ccl 2405
  catalog-info.yaml
Labels: patch

#224 Add resource policy to event bus.
  modules/aws/event_bridge/event_bridge_rule/README.md
  modules/aws/event_bridge/event_bridge_rule/main.tf
  modules/aws/event_bridge/event_bridge_rule/variables.tf
Labels: minor

#225 CCL-2324: DNS Zone creation and delegation
  modules/aws/networking/dns/r53-public-zone/main.tf
  modules/aws/networking/dns/r53-public-zone/outputs.tf
  modules/aws/networking/dns/r53-public-zone/variables.tf
  modules/aws/networking/dns/zone-delegation/main.tf
  modules/aws/networking/dns/zone-delegation/variables.tf
Labels: major

#226 CCL-2138 - Adjusting system name to non capital
  catalog-info.yaml
Labels: patch
